// Interface automatically generated by schemas-to-ts

export enum Status {
  Active = 'active',
  Finished = 'finished',
  Cancelled = 'cancelled',}

export interface Order {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    stripeId?: string;
    products?: any;
    paymentMethod?: string;
    orderId: string;
    addressInfo: any;
    user?: string;
    totalPrice?: number;
    isPaid?: boolean;
    credentialsInfo: any;
    billingAddressInfo?: any;
    status: Status;
  };
}
export interface Order_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  stripeId?: string;
  products?: any;
  paymentMethod?: string;
  orderId: string;
  addressInfo: any;
  user?: string;
  totalPrice?: number;
  isPaid?: boolean;
  credentialsInfo: any;
  billingAddressInfo?: any;
  status: Status;
}

export interface Order_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  stripeId?: string;
  products?: any;
  paymentMethod?: string;
  orderId: string;
  addressInfo: any;
  user?: string;
  totalPrice?: number;
  isPaid?: boolean;
  credentialsInfo: any;
  billingAddressInfo?: any;
  status: Status;
}

export interface Order_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  stripeId?: string;
  products?: any;
  paymentMethod?: string;
  orderId: string;
  addressInfo: any;
  user?: string;
  totalPrice?: number;
  isPaid?: boolean;
  credentialsInfo: any;
  billingAddressInfo?: any;
  status: Status;
}
