// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Blog {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    minutesRead: number;
    summary?: string;
    isFeatured?: boolean;
    thumbnail: { data: Media };
    image: { data: Media };
    content: string;
    locale: string;
    localizations?: { data: Blog[] };
  };
}
export interface Blog_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  minutesRead: number;
  summary?: string;
  isFeatured?: boolean;
  thumbnail: Media;
  image: Media;
  content: string;
  locale: string;
  localizations?: Blog[];
}

export interface Blog_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  minutesRead: number;
  summary?: string;
  isFeatured?: boolean;
  thumbnail: number;
  image: number;
  content: string;
  locale: string;
  localizations?: Blog[];
}

export interface Blog_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  minutesRead: number;
  summary?: string;
  isFeatured?: boolean;
  thumbnail: AdminPanelRelationPropertyModification<Media>;
  image: AdminPanelRelationPropertyModification<Media>;
  content: string;
  locale: string;
  localizations?: Blog[];
}
