// Interface automatically generated by schemas-to-ts

export interface Subscription {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    email: string;
    locale: string;
    localizations?: { data: Subscription[] };
  };
}
export interface Subscription_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  email: string;
  locale: string;
  localizations?: Subscription[];
}

export interface Subscription_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  email: string;
  locale: string;
  localizations?: Subscription[];
}

export interface Subscription_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  email: string;
  locale: string;
  localizations?: Subscription[];
}
