// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Category } from '../../../category/content-types/category/category';
import { Category_Plain } from '../../../category/content-types/category/category';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Product {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    subtitle?: string;
    price: number;
    description?: string;
    size: any;
    image?: { data: Media[] };
    thumbnail: { data: Media };
    original_price?: number;
    slug?: string;
    categories?: { data: Category[] };
    productSlider?: { data: Media[] };
    amount: number;
    outOfStock?: boolean;
    locale: string;
    localizations?: { data: Product[] };
  };
}
export interface Product_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  subtitle?: string;
  price: number;
  description?: string;
  size: any;
  image?: Media[];
  thumbnail: Media;
  original_price?: number;
  slug?: string;
  categories?: Category_Plain[];
  productSlider?: Media[];
  amount: number;
  outOfStock?: boolean;
  locale: string;
  localizations?: Product[];
}

export interface Product_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  subtitle?: string;
  price: number;
  description?: string;
  size: any;
  image?: number[];
  thumbnail: number;
  original_price?: number;
  slug?: string;
  categories?: number[];
  productSlider?: number[];
  amount: number;
  outOfStock?: boolean;
  locale: string;
  localizations?: Product[];
}

export interface Product_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  subtitle?: string;
  price: number;
  description?: string;
  size: any;
  image?: AdminPanelRelationPropertyModification<Media>[];
  thumbnail: AdminPanelRelationPropertyModification<Media>;
  original_price?: number;
  slug?: string;
  categories?: AdminPanelRelationPropertyModification<Category_Plain>;
  productSlider?: AdminPanelRelationPropertyModification<Media>[];
  amount: number;
  outOfStock?: boolean;
  locale: string;
  localizations?: Product[];
}
